version: '3.8'

services:

  frontend:
    image: nginx:bbr
    container_name: frontend
    environment:
      DOCKER: 'true'
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - default

networks:
  default:
    external: true
    name: humle_net
